### ISSUE TITLE
DPL-767 [BUG] smwf Memory leak

### ISSUE THREAD

**Issue by emrojo** [sanger/sm_workflow_lims#320]
**Describe the bug**
There is a memory leak on sm workflow lims that makes it run out of memory. This is the times when the event happened in the past:
```
[Thu May 20 06:24:27 2021] Out of memory: Kill process 22210 (ruby) score 398 or sacrifice child
[Tue Aug 31 15:28:10 2021] Out of memory: Kill process 22146 (ruby) score 359 or sacrifice child
[Fri Dec 10 14:58:39 2021] Out of memory: Kill process 22226 (ruby) score 324 or sacrifice child
[Mon Jun 27 16:42:17 2022] Out of memory: Kill process 23246 (ruby) score 418 or sacrifice child
[Fri Jul  1 11:48:50 2022] Out of memory: Kill process 23242 (ruby) score 293 or sacrifice child
[Fri Jul  1 12:01:48 2022] Out of memory: Kill process 23248 (ruby) score 323 or sacrifice child
[Mon Jul  4 15:49:07 2022] Out of memory: Kill process 3878 (ruby) score 390 or sacrifice child
[Fri Sep  9 11:05:51 2022] Out of memory: Kill process 26120 (ruby) score 334 or sacrifice child
[Thu Sep 15 19:53:00 2022] Out of memory: Kill process 26123 (ruby) score 313 or sacrifice child
[Fri Oct 21 09:04:02 2022] Out of memory: Kill process 26125 (ruby) score 267 or sacrifice child
[Mon Nov 28 18:29:36 2022] Out of memory: Kill process 19847 (ruby) score 276 or sacrifice child
[Thu Mar  2 17:23:47 2023] Out of memory: Kill process 26122 (ruby) score 314 or sacrifice child
[Thu May 11 09:48:23 2023] Out of memory: Kill process 1651 (ruby) score 416 or sacrifice child
```

Labwhere do have a similar issue which it has been handled by restarting the server when memory goes too high. We could adopt the same solution in here <https://github.com/sanger/deployment/blob/master/roles/deploy_labwhere/templates/puma_monit_memory_check.j2>

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by SujitDey2022** [comment]
@emrojo please confirm if this bus is still valid and needs to be triaged in the prioritisation meeting?
