### ISSUE TITLE
BUG - Mini LIMS doesn't accept tube rack barcodes

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sm_workflow_lims#87]
From Danni:

I tested putting these plates into miniLIMS and have come across an issue. When I created a new batch I must enter the plate barcode ID (this will be rack ID), miniLIMs does not like have letters in the plate ID box. The issue with is, this prefix can change as it is chosen by the manufacturer and after speaking to Rich C he believes the SSR’s do need this prefix information.

![image](https://user-images.githubusercontent.com/10407809/78132430-a551f080-7414-11ea-85d5-435fca2ac833.png)

![image](https://user-images.githubusercontent.com/10407809/78132442-a8e57780-7414-11ea-9ee5-d04db9876792.png)

**Comment by stevieing** [comment]
Fairly simple fix.
The AssetType presenter validates the barcode using validates_with.
Depends on the asset_type. If it is sample management it expects it to be numeric.
Fix is to change the AssetTypeFactory for sample management identifier_data_type from 'numeric' to 'alphanumeric'.
